# Generated by Django 4.0.4 on 2022-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='full_data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(unique=True)),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('local', models.IntegerField()),
                ('service', models.IntegerField()),
                ('service_name', models.CharField(max_length=20)),
                ('season_profit', models.IntegerField()),
                ('season_count', models.IntegerField()),
                ('week_rate', models.IntegerField()),
                ('week_count', models.IntegerField()),
                ('weeken_rate', models.IntegerField()),
                ('weeken_count', models.IntegerField()),
                ('male_rate', models.IntegerField()),
                ('male_count', models.IntegerField()),
                ('female_rate', models.IntegerField()),
                ('female_count', models.IntegerField()),
                ('day_rate', models.IntegerField()),
                ('day_count', models.IntegerField()),
                ('night_rate', models.IntegerField()),
                ('night_count', models.IntegerField()),
                ('young_rate', models.IntegerField()),
                ('young_count', models.IntegerField()),
                ('youth_rate', models.IntegerField()),
                ('youth_count', models.IntegerField()),
                ('elder_rate', models.IntegerField()),
                ('elder_count', models.IntegerField()),
                ('old_rate', models.IntegerField()),
                ('old_count', models.IntegerField()),
                ('gu', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locate_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city', models.CharField(max_length=20)),
                ('gu', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='realty_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(unique=True)),
                ('bd_type1', models.CharField(max_length=6)),
                ('bd_type2', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=10)),
                ('gu', models.CharField(max_length=10)),
                ('dong', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('trade_type', models.CharField(max_length=6)),
                ('deposit', models.IntegerField()),
                ('month_price', models.IntegerField()),
                ('leasable_area', models.IntegerField()),
                ('total_area', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('total_floor', models.IntegerField()),
                ('direction', models.CharField(max_length=5)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
    ]
