# Generated by Django 4.0.4 on 2022-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_full_data_model_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_data_model',
            name='service_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
